var namespaceptof_1_1model__periodic__cartesian__advection__diffusion__decay__catalytic__2d__parallel =
[
    [ "Model", "d3/d98/structptof_1_1model__periodic__cartesian__advection__diffusion__decay__catalytic__2d__parallel_1_1_model.html", "d3/d98/structptof_1_1model__periodic__cartesian__advection__diffusion__decay__catalytic__2d__parallel_1_1_model" ],
    [ "makeTransitions", "de/d88/namespaceptof_1_1model__periodic__cartesian__advection__diffusion__decay__catalytic__2d__parallel.html#a7c0d54ac5df8c1cc662e9d4b794ffc15", null ]
];