var hierarchy =
[
    [ "ptof::Boundary_Cases< Locator, Store_Info, Boundary_Periodic, Boundary_Custom, SurfaceReaction >", "d4/d49/classptof_1_1_boundary___cases.html", null ],
    [ "geometry::Boundary_DoNothing", "dd/d2e/classgeometry_1_1_boundary___do_nothing.html", null ],
    [ "ptof::Boundary_DoNothing", "d6/d3e/structptof_1_1_boundary___do_nothing.html", null ],
    [ "geometry::Boundary_Open_RadialReflecting_3d< dd_open >", "d8/d86/classgeometry_1_1_boundary___open___radial_reflecting__3d.html", null ],
    [ "geometry::Boundary_Periodic", "d7/d27/classgeometry_1_1_boundary___periodic.html", null ],
    [ "geometry::Boundary_Periodic_1d", "d3/d11/classgeometry_1_1_boundary___periodic__1d.html", null ],
    [ "geometry::Boundary_Periodic_Dim< dd >", "db/de1/classgeometry_1_1_boundary___periodic___dim.html", null ],
    [ "ptof::Boundary_Periodic_OF< Boundary, Locator >", "df/d60/structptof_1_1_boundary___periodic___o_f.html", null ],
    [ "geometry::Boundary_Periodic_SymmetryPlanes< SymmetryPlanes >", "d8/d63/classgeometry_1_1_boundary___periodic___symmetry_planes.html", null ],
    [ "geometry::Boundary_Periodic_SymmetryPlanes_WithOutsideInfo< SymmetryPlanes >", "df/de8/classgeometry_1_1_boundary___periodic___symmetry_planes___with_outside_info.html", null ],
    [ "geometry::Boundary_Periodic_WithOutsideInfo", "db/d57/classgeometry_1_1_boundary___periodic___with_outside_info.html", null ],
    [ "geometry::Boundary_RadialReflecting_2d", "d2/d11/classgeometry_1_1_boundary___radial_reflecting__2d.html", null ],
    [ "geometry::Boundary_Reflecting", "df/d3c/classgeometry_1_1_boundary___reflecting.html", null ],
    [ "geometry::Boundary_Reflecting_1d", "df/d79/classgeometry_1_1_boundary___reflecting__1d.html", null ],
    [ "geometry::Boundary_Reflecting_Dim< dd >", "db/de4/classgeometry_1_1_boundary___reflecting___dim.html", null ],
    [ "ptof::Boundary_Reinject< InitialCondition >", "d4/d7b/structptof_1_1_boundary___reinject.html", null ],
    [ "ptof::BoundaryCondition", "d2/d5e/structptof_1_1_boundary_condition.html", null ],
    [ "ptof::BoundaryConditionSet", "d6/dd9/structptof_1_1_boundary_condition_set.html", null ],
    [ "useful::build_indices< size >", "d0/d5b/structuseful_1_1build__indices.html", null ],
    [ "useful::build_indices< 0 >", "dd/d78/structuseful_1_1build__indices_3_010_01_4.html", null ],
    [ "useful::Creator< T >", "d5/d03/structuseful_1_1_creator.html", null ],
    [ "ptof::Criterion< Subject >", "d9/d13/structptof_1_1_criterion.html", [
      [ "ptof::Criterion_all_absorbed< Subject >", "da/d25/structptof_1_1_criterion__all__absorbed.html", null ],
      [ "ptof::Criterion_fraction_absorbed< Subject >", "d4/d26/structptof_1_1_criterion__fraction__absorbed.html", null ],
      [ "ptof::Criterion_mass_above< Subject >", "d0/d36/structptof_1_1_criterion__mass__above.html", null ],
      [ "ptof::Criterion_mass_below< Subject >", "da/df1/structptof_1_1_criterion__mass__below.html", null ],
      [ "ptof::Criterion_one_absorbed< Subject >", "dc/df3/structptof_1_1_criterion__one__absorbed.html", null ],
      [ "ptof::Criterion_time< Subject >", "da/d6e/structptof_1_1_criterion__time.html", null ]
    ] ],
    [ "ctrw::CTRW< State_t >", "d2/dd2/classctrw_1_1_c_t_r_w.html", null ],
    [ "ctrw::CTRW_Parallel< State_t >", "d7/dfc/classctrw_1_1_c_t_r_w___parallel.html", null ],
    [ "ptof::Directories", "df/d68/structptof_1_1_directories.html", null ],
    [ "ptof::DirectoriesOF", "d1/d82/structptof_1_1_directories_o_f.html", null ],
    [ "useful::DoFalse", "d0/d9c/structuseful_1_1_do_false.html", null ],
    [ "geometry::Domain< Shape >", "d5/db2/structgeometry_1_1_domain.html", null ],
    [ "useful::DoNothing", "db/d72/structuseful_1_1_do_nothing.html", null ],
    [ "useful::DoTrue", "df/df3/structuseful_1_1_do_true.html", null ],
    [ "useful::Empty", "da/d86/structuseful_1_1_empty.html", null ],
    [ "ptof::EndCriterion", "dd/d0d/structptof_1_1_end_criterion.html", null ],
    [ "std::false_type", null, [
      [ "ptof::Has_periodicity< State, typename >", "d4/db0/structptof_1_1_has__periodicity.html", null ],
      [ "useful::can_call_abs< typename, Args >", "d9/d78/structuseful_1_1can__call__abs.html", null ],
      [ "useful::can_call_sqrt< typename, Args >", "d8/d23/structuseful_1_1can__call__sqrt.html", null ],
      [ "useful::details::has_method< Z, types, class >", "d9/df8/structuseful_1_1details_1_1has__method.html", null ]
    ] ],
    [ "useful::Forward< Object_Type >", "df/d34/structuseful_1_1_forward.html", null ],
    [ "useful::Forward< double >", "df/d34/structuseful_1_1_forward.html", null ],
    [ "useful::Forward_ref< Object_Type >", "d6/d37/structuseful_1_1_forward__ref.html", null ],
    [ "range::gen< Type >", "d0/d5d/structrange_1_1gen.html", null ],
    [ "ptof::Geometry< dim_val, dynamics >", "dc/d30/structptof_1_1_geometry.html", null ],
    [ "ptof::Geometry_Bcc< dim_val, dynamics, periodicity_type >", "da/d9d/structptof_1_1_geometry___bcc.html", null ],
    [ "ptof::Geometry_Bcc_Parallel< dim_val, dynamics, periodicity_type >", "d1/d3e/structptof_1_1_geometry___bcc___parallel.html", null ],
    [ "ptof::Geometry_Parallel< dim_val, dynamics >", "df/dfc/structptof_1_1_geometry___parallel.html", null ],
    [ "ptof::Geometry_Periodic_Cartesian< dim_val, dynamics >", "d2/d99/structptof_1_1_geometry___periodic___cartesian.html", null ],
    [ "ptof::Geometry_Periodic_Cartesian_Parallel< dim_val, dynamics >", "df/dae/structptof_1_1_geometry___periodic___cartesian___parallel.html", null ],
    [ "ctrw::Get_dist_sq", "d2/d87/structctrw_1_1_get__dist__sq.html", null ],
    [ "ctrw::Get_from_particle< Getter >", "dd/db1/structctrw_1_1_get__from__particle.html", null ],
    [ "ctrw::Get_mass", "de/d1b/structctrw_1_1_get__mass.html", null ],
    [ "ctrw::Get_new< Getter >", "d0/dc3/structctrw_1_1_get__new.html", null ],
    [ "ctrw::Get_new_from_particle< Getter >", "dc/d51/structctrw_1_1_get__new__from__particle.html", null ],
    [ "ctrw::Get_old< Getter >", "dd/d08/structctrw_1_1_get__old.html", null ],
    [ "ctrw::Get_old_from_particle< Getter >", "db/df8/structctrw_1_1_get__old__from__particle.html", null ],
    [ "ctrw::Get_position", "d9/dca/structctrw_1_1_get__position.html", null ],
    [ "ctrw::Get_position_component< dd >", "d0/d8e/structctrw_1_1_get__position__component.html", null ],
    [ "ctrw::Get_position_component_arg", "de/d54/structctrw_1_1_get__position__component__arg.html", null ],
    [ "ctrw::Get_position_component_sq< dd >", "df/d0b/structctrw_1_1_get__position__component__sq.html", null ],
    [ "ctrw::Get_position_interp_velocity< Getter, Getter_velocity >", "d7/d1a/structctrw_1_1_get__position__interp__velocity.html", null ],
    [ "ctrw::Get_position_periodic< Boundary >", "dd/dd1/structctrw_1_1_get__position__periodic.html", null ],
    [ "ctrw::Get_position_periodic< Boundary const & >", "dd/dd1/structctrw_1_1_get__position__periodic.html", null ],
    [ "ctrw::Get_position_periodic_cartesian", "d7/dda/structctrw_1_1_get__position__periodic__cartesian.html", null ],
    [ "ctrw::Get_position_periodic_cartesian_component< dd >", "d4/d43/structctrw_1_1_get__position__periodic__cartesian__component.html", null ],
    [ "ctrw::Get_position_periodic_cartesian_projection", "d9/d7f/structctrw_1_1_get__position__periodic__cartesian__projection.html", null ],
    [ "ctrw::Get_position_projection", "da/dd1/structctrw_1_1_get__position__projection.html", null ],
    [ "ctrw::Get_position_property< Property >", "d0/d9a/structctrw_1_1_get__position__property.html", null ],
    [ "ctrw::Get_projection< Getter >", "df/de2/structctrw_1_1_get__projection.html", null ],
    [ "ctrw::Get_tag", "d5/daf/structctrw_1_1_get__tag.html", null ],
    [ "ctrw::Get_time", "da/dad/structctrw_1_1_get__time.html", null ],
    [ "ctrw::Get_time_interp_velocity< Getter, VelocityMapper >", "d5/d10/structctrw_1_1_get__time__interp__velocity.html", null ],
    [ "ctrw::Get_velocity", "d1/d4e/structctrw_1_1_get__velocity.html", null ],
    [ "ctrw::Get_velocity_component< dd >", "de/d39/structctrw_1_1_get__velocity__component.html", null ],
    [ "ctrw::Get_velocity_property< Property >", "d9/d1a/structctrw_1_1_get__velocity__property.html", null ],
    [ "has_periodicidity", "d5/d14/classhas__periodicidity.html", null ],
    [ "useful::has_periodicity< T >", "dd/d08/structuseful_1_1has__periodicity.html", null ],
    [ "useful::has_time_step< T >", "d5/dc6/structuseful_1_1has__time__step.html", null ],
    [ "useful::has_time_step_getter< T >", "dc/d7c/structuseful_1_1has__time__step__getter.html", null ],
    [ "useful::has_time_step_setter< T >", "d5/d31/structuseful_1_1has__time__step__setter.html", null ],
    [ "useful::has_value_type< T >", "d3/d44/classuseful_1_1has__value__type.html", null ],
    [ "useful::hash_container< Container >", "d4/de0/structuseful_1_1hash__container.html", null ],
    [ "useful::hash_pair< S, T >", "dc/d50/structuseful_1_1hash__pair.html", null ],
    [ "useful::indices< Indices >", "d1/d28/structuseful_1_1indices.html", null ],
    [ "ptof::Info_Absorbed", "d6/df0/structptof_1_1_info___absorbed.html", null ],
    [ "ptof::Info_Absorbed_Reinjections", "dc/d06/structptof_1_1_info___absorbed___reinjections.html", null ],
    [ "Info_type", "d4/d6e/struct_info__type.html", null ],
    [ "ptof::Info_Type", "d8/d13/structptof_1_1_info___type.html", null ],
    [ "ptof::model_advection_diffusion_2d::InitialCondition< CTRW >", "df/d07/structptof_1_1model__advection__diffusion__2d_1_1_initial_condition.html", null ],
    [ "ptof::InitialCondition_Cases< Geometry, VelocityField, ParticleMaker, Parameters, Mask >", "db/dfb/classptof_1_1_initial_condition___cases.html", null ],
    [ "ptof::InitialConditions", "d5/d77/structptof_1_1_initial_conditions.html", null ],
    [ "ctrw::JumpGenerator_Add< JumpGenerator_1, JumpGenerator_2 >", "d8/dd5/classctrw_1_1_jump_generator___add.html", null ],
    [ "ctrw::JumpGenerator_Diffusion", "df/d00/classctrw_1_1_jump_generator___diffusion.html", null ],
    [ "ctrw::JumpGenerator_Diffusion_1d< RNG >", "d1/d8b/classctrw_1_1_jump_generator___diffusion__1d.html", null ],
    [ "ctrw::JumpGenerator_Diffusion_1d< std::mt19937 >", "d1/d8b/classctrw_1_1_jump_generator___diffusion__1d.html", null ],
    [ "ctrw::JumpGenerator_JumpAngle_2d", "d4/def/classctrw_1_1_jump_generator___jump_angle__2d.html", null ],
    [ "ctrw::JumpGenerator_RW_1d< Distance_type, RNG >", "dd/d88/classctrw_1_1_jump_generator___r_w__1d.html", null ],
    [ "ctrw::JumpGenerator_Step< Step >", "d3/da3/classctrw_1_1_jump_generator___step.html", null ],
    [ "ctrw::JumpGenerator_Uniform_1d< RNG >", "d1/d43/classctrw_1_1_jump_generator___uniform__1d.html", null ],
    [ "ctrw::JumpGenerator_Velocity< VelocityField >", "d3/d4c/classctrw_1_1_jump_generator___velocity.html", null ],
    [ "ctrw::JumpGenerator_Velocity_RK4< VelocityField, Boundary >", "df/dcd/classctrw_1_1_jump_generator___velocity___r_k4.html", null ],
    [ "useful::notstd::left_shift", "db/dc4/structuseful_1_1notstd_1_1left__shift.html", null ],
    [ "ptof::Locator_Cell", "d0/d4f/structptof_1_1_locator___cell.html", null ],
    [ "ptof::Locator_Cell_Parallel", "d5/db8/structptof_1_1_locator___cell___parallel.html", null ],
    [ "useful::Maker< Object >", "dc/d8a/structuseful_1_1_maker.html", null ],
    [ "ptof::Measure", "dd/ddd/structptof_1_1_measure.html", null ],
    [ "ptof::MeasureSpacing", "d4/dd7/structptof_1_1_measure_spacing.html", null ],
    [ "ptof::MeasureSpacingUnits", "d2/d80/structptof_1_1_measure_spacing_units.html", null ],
    [ "ptof::model_advection_2d::Model", "d3/df2/structptof_1_1model__advection__2d_1_1_model.html", null ],
    [ "ptof::model_advection_2d_parallel::Model", "d0/d0f/structptof_1_1model__advection__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_3d::Model", "dc/d30/structptof_1_1model__advection__3d_1_1_model.html", null ],
    [ "ptof::model_advection_3d_parallel::Model", "d6/d50/structptof_1_1model__advection__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_2d::Model", "d8/d28/structptof_1_1model__advection__diffusion__2d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_2d_parallel::Model", "d2/d0a/structptof_1_1model__advection__diffusion__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_3d::Model", "d3/df7/structptof_1_1model__advection__diffusion__3d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_3d_parallel::Model", "d3/df6/structptof_1_1model__advection__diffusion__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_fpt_2d::Model", "db/d89/structptof_1_1model__advection__diffusion__fpt__2d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_fpt_2d_parallel::Model", "d7/db8/structptof_1_1model__advection__diffusion__fpt__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_fpt_3d::Model", "d8/d2a/structptof_1_1model__advection__diffusion__fpt__3d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_fpt_3d_parallel::Model", "dc/d6c/structptof_1_1model__advection__diffusion__fpt__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_2d::Model", "d0/da7/structptof_1_1model__advection__diffusion__surface__decay__2d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_2d_parallel::Model", "db/da2/structptof_1_1model__advection__diffusion__surface__decay__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_3d::Model", "d6/d5a/structptof_1_1model__advection__diffusion__surface__decay__3d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_3d_parallel::Model", "d0/da6/structptof_1_1model__advection__diffusion__surface__decay__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection::Model", "dd/d1b/structptof_1_1model__bcc__cartesian__advection_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion::Model", "d2/da9/structptof_1_1model__bcc__cartesian__advection__diffusion_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_fpt::Model", "db/d65/structptof_1_1model__bcc__cartesian__advection__diffusion__fpt_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_fpt_parallel::Model", "d6/d55/structptof_1_1model__bcc__cartesian__advection__diffusion__fpt__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_parallel::Model", "df/d52/structptof_1_1model__bcc__cartesian__advection__diffusion__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_surface_decay::Model", "d5/d44/structptof_1_1model__bcc__cartesian__advection__diffusion__surface__decay_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_surface_decay_parallel::Model", "d6/dfa/structptof_1_1model__bcc__cartesian__advection__diffusion__surface__decay__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_parallel::Model", "dc/d22/structptof_1_1model__bcc__cartesian__advection__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection::Model", "dd/d30/structptof_1_1model__bcc__symmetryplanes__advection_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion::Model", "db/d17/structptof_1_1model__bcc__symmetryplanes__advection__diffusion_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_fpt::Model", "d8/d11/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__fpt_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_fpt_parallel::Model", "d8/d8d/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__fpt__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_parallel::Model", "d8/d58/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_surface_decay::Model", "d1/dd3/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__surface__decay_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_surface_decay_parallel::Model", "da/d03/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__surface__decay__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_parallel::Model", "d6/d83/structptof_1_1model__bcc__symmetryplanes__advection__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_2d::Model", "de/dd4/structptof_1_1model__periodic__cartesian__advection__2d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_2d_parallel::Model", "d3/dd9/structptof_1_1model__periodic__cartesian__advection__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_3d::Model", "d5/d4f/structptof_1_1model__periodic__cartesian__advection__3d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_3d_parallel::Model", "d5/db1/structptof_1_1model__periodic__cartesian__advection__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_2d::Model", "d3/da7/structptof_1_1model__periodic__cartesian__advection__diffusion__2d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_2d_parallel::Model", "da/d86/structptof_1_1model__periodic__cartesian__advection__diffusion__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_3d::Model", "d5/d26/structptof_1_1model__periodic__cartesian__advection__diffusion__3d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_3d_parallel::Model", "d7/d62/structptof_1_1model__periodic__cartesian__advection__diffusion__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_fpt_2d::Model", "dc/d39/structptof_1_1model__periodic__cartesian__advection__diffusion__fpt__2d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_fpt_2d_parallel::Model", "d2/dcd/structptof_1_1model__periodic__cartesian__advection__diffusion__fpt__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_fpt_3d::Model", "dc/d32/structptof_1_1model__periodic__cartesian__advection__diffusion__fpt__3d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_fpt_3d_parallel::Model", "d0/d77/structptof_1_1model__periodic__cartesian__advection__diffusion__fpt__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_surface_decay_2d::Model", "de/dd0/structptof_1_1model__periodic__cartesian__advection__diffusion__surface__decay__2d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_surface_decay_2d_parallel::Model", "df/d2e/structptof_1_1model__periodic__cartesian__advection__diffusion__surface__decay__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_surface_decay_3d::Model", "d1/d0c/structptof_1_1model__periodic__cartesian__advection__diffusion__surface__decay__3d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_surface_decay_3d_parallel::Model", "d1/d26/structptof_1_1model__periodic__cartesian__advection__diffusion__surface__decay__3d__parallel_1_1_model.html", null ],
    [ "useful::MultiArray< value_t >", "dc/d1a/classuseful_1_1_multi_array.html", null ],
    [ "NextMeasureTime", "de/da1/struct_output___cases_1_1_next_measure_time.html", null ],
    [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::NextMeasureTime", "de/da7/structptof_1_1_output___cases_1_1_next_measure_time.html", [
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::NextMeasureTime_linear", "dc/d4b/structptof_1_1_output___cases_1_1_next_measure_time__linear.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::NextMeasureTime_log", "d6/de0/structptof_1_1_output___cases_1_1_next_measure_time__log.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::NextMeasureTime_step", "db/de3/structptof_1_1_output___cases_1_1_next_measure_time__step.html", null ]
    ] ],
    [ "NextMeasureTime_log", "de/d81/struct_output___cases_1_1_next_measure_time__log.html", null ],
    [ "NextMeasureTime_step", "d6/d19/struct_output___cases_1_1_next_measure_time__step.html", null ],
    [ "useful::has_value_type< T >::One", "db/db2/structuseful_1_1has__value__type_1_1_one.html", null ],
    [ "useful::op_valid_impl< X, Y, Op >", "d2/d99/structuseful_1_1op__valid__impl.html", null ],
    [ "useful::notstd::operator_and", "dd/d5e/structuseful_1_1notstd_1_1operator__and.html", null ],
    [ "ctrw::OrientationGenerator_Flip", "d0/d3d/classctrw_1_1_orientation_generator___flip.html", null ],
    [ "ctrw::OrientationGenerator_Gradient_1d< Concentration, Gradient, RNG >", "d0/d34/classctrw_1_1_orientation_generator___gradient__1d.html", null ],
    [ "Output", "d3/dc7/struct_output___cases_1_1_output.html", null ],
    [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output", "d0/d91/structptof_1_1_output___cases_1_1_output.html", [
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_absorption_time", "d8/d3c/structptof_1_1_output___cases_1_1_output__absorption__time.html", null ]
    ] ],
    [ "Output_absorption_time", "d6/da2/struct_output___cases_1_1_output__absorption__time.html", null ],
    [ "ptof::Output_Cases< Subject, VelocityField, Geometry >", "d5/de8/classptof_1_1_output___cases.html", null ],
    [ "Output_mass", "de/d7f/struct_output___cases_1_1_output__mass.html", null ],
    [ "Output_mass_in_regions", "de/d9c/class_output___cases_1_1_output__mass__in__regions.html", null ],
    [ "Output_position", "df/d5e/struct_output___cases_1_1_output__position.html", null ],
    [ "Output_position_in_regions", "dc/dfc/class_output___cases_1_1_output__position__in__regions.html", null ],
    [ "Output_position_mean", "d6/d70/struct_output___cases_1_1_output__position__mean.html", null ],
    [ "Output_position_mean_periodic", "da/dbc/class_output___cases_1_1_output__position__mean__periodic.html", null ],
    [ "Output_position_periodic", "d8/d7a/class_output___cases_1_1_output__position__periodic.html", null ],
    [ "Output_position_second_moment", "db/d24/struct_output___cases_1_1_output__position__second__moment.html", null ],
    [ "Output_position_second_moment_periodic", "d5/d3a/class_output___cases_1_1_output__position__second__moment__periodic.html", null ],
    [ "Output_position_variance", "dd/d84/struct_output___cases_1_1_output__position__variance.html", null ],
    [ "Output_position_variance_periodic", "d7/d3d/class_output___cases_1_1_output__position__variance__periodic.html", null ],
    [ "Output_pressure", "de/dd7/struct_output___cases_1_1_output__pressure.html", null ],
    [ "Output_velocity", "d7/da1/struct_output___cases_1_1_output__velocity.html", null ],
    [ "Output_velocity_gradient", "de/dc2/struct_output___cases_1_1_output__velocity__gradient.html", null ],
    [ "OutputTime", "da/d2f/struct_output___cases_1_1_output_time.html", null ],
    [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::OutputTime", "d2/d71/structptof_1_1_output___cases_1_1_output_time.html", [
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_mass", "d3/da0/structptof_1_1_output___cases_1_1_output__mass.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_mass_in_regions< Mask >", "dd/d8c/structptof_1_1_output___cases_1_1_output__mass__in__regions.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position", "d3/ded/structptof_1_1_output___cases_1_1_output__position.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position_in_regions< Mask >", "dd/dd4/structptof_1_1_output___cases_1_1_output__position__in__regions.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position_mean", "d1/d2d/structptof_1_1_output___cases_1_1_output__position__mean.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position_mean_periodic< Boundary >", "d3/d02/structptof_1_1_output___cases_1_1_output__position__mean__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position_periodic< Boundary >", "d3/d84/structptof_1_1_output___cases_1_1_output__position__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position_second_moment", "dc/dc1/structptof_1_1_output___cases_1_1_output__position__second__moment.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position_second_moment_periodic< Boundary >", "da/d6d/structptof_1_1_output___cases_1_1_output__position__second__moment__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position_variance", "d5/d2b/structptof_1_1_output___cases_1_1_output__position__variance.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_position_variance_periodic< Boundary >", "d7/dc2/structptof_1_1_output___cases_1_1_output__position__variance__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_pressure", "d9/d3d/structptof_1_1_output___cases_1_1_output__pressure.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_velocity", "df/d5f/structptof_1_1_output___cases_1_1_output__velocity.html", null ],
      [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Output_velocity_gradient", "d0/d75/structptof_1_1_output___cases_1_1_output__velocity__gradient.html", null ]
    ] ],
    [ "geometry::Parallelepiped< Position_t >", "d4/d45/structgeometry_1_1_parallelepiped.html", null ],
    [ "Parameters", "d8/d4a/struct_output___cases_1_1_parameters.html", null ],
    [ "Parameters", "d4/d48/struct_phase_1_1_parameters.html", null ],
    [ "ptof::model_advection_2d::Solvers::Parameters", "d6/d3d/structptof_1_1model__advection__2d_1_1_solvers_1_1_parameters.html", null ],
    [ "ptof::model_advection_2d::Transport::Parameters", "d8/d0b/structptof_1_1model__advection__2d_1_1_transport_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_2d::InitialCondition< CTRW >::Parameters", "dd/d96/structptof_1_1model__advection__diffusion__2d_1_1_initial_condition_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_2d::Reaction::Parameters", "de/d70/structptof_1_1model__advection__diffusion__2d_1_1_reaction_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_2d::Solvers::Parameters", "dc/d05/structptof_1_1model__advection__diffusion__2d_1_1_solvers_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_2d::Transport::Parameters", "dc/d6a/structptof_1_1model__advection__diffusion__2d_1_1_transport_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_2d::Reaction::Parameters", "d2/d04/structptof_1_1model__advection__diffusion__surface__decay__2d_1_1_reaction_1_1_parameters.html", null ],
    [ "ptof::model_bcc_cartesian_advection::Transport::Parameters", "db/d87/structptof_1_1model__bcc__cartesian__advection_1_1_transport_1_1_parameters.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion::Transport::Parameters", "d4/d16/structptof_1_1model__bcc__cartesian__advection__diffusion_1_1_transport_1_1_parameters.html", null ],
    [ "ptof::Output_Cases< Subject, VelocityField, Geometry >::Parameters", "dd/dc8/structptof_1_1_output___cases_1_1_parameters.html", null ],
    [ "ptof::Phase::Parameters", "de/d93/structptof_1_1_phase_1_1_parameters.html", null ],
    [ "useful::Parameters_or_empty< bool, typename >", "df/d19/structuseful_1_1_parameters__or__empty.html", null ],
    [ "useful::Parameters_or_empty< true, T >", "d4/d06/structuseful_1_1_parameters__or__empty_3_01true_00_01_t_01_4.html", null ],
    [ "ctrw::Particle< State_t >", "d5/d4b/classctrw_1_1_particle.html", null ],
    [ "ptof::ParticleMaker< Particle, Locator >", "da/dae/structptof_1_1_particle_maker.html", null ],
    [ "ptof::ParticleMaker_Periodic< Particle, Locator, Boundary >", "d5/d84/structptof_1_1_particle_maker___periodic.html", null ],
    [ "ptof::Phase", "d0/d06/structptof_1_1_phase.html", null ],
    [ "ptof::InitialCondition_Cases< Geometry, VelocityField, ParticleMaker, Parameters, Mask >::PositionMaker", "dc/dab/structptof_1_1_initial_condition___cases_1_1_position_maker.html", null ],
    [ "ptof::model_advection_diffusion_2d::Reaction", "d4/d50/structptof_1_1model__advection__diffusion__2d_1_1_reaction.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_2d::Reaction", "d2/dcb/structptof_1_1model__advection__diffusion__surface__decay__2d_1_1_reaction.html", null ],
    [ "ptof::Reaction_DoNothing", "da/dfd/classptof_1_1_reaction___do_nothing.html", null ],
    [ "useful::notstd::right_shift", "db/dc9/structuseful_1_1notstd_1_1right__shift.html", null ],
    [ "ptof::ScalarField_LinearInterpolation_OF< Field, Locator, check_if_outside, warn_if_outside, Uninterpolated >", "d6/d57/classptof_1_1_scalar_field___linear_interpolation___o_f.html", null ],
    [ "ptof::ScalarField_LinearInterpolation_OF< Foam::volScalarField, typename ptof::Locator_Cell const &, 1, 1 >", "d6/d57/classptof_1_1_scalar_field___linear_interpolation___o_f.html", null ],
    [ "useful::Selector< TT, >", "d7/dd2/structuseful_1_1_selector.html", null ],
    [ "useful::Selector_t< TT >", "d3/d42/structuseful_1_1_selector__t.html", null ],
    [ "ptof::model_advection_2d::Solvers", "df/d8b/structptof_1_1model__advection__2d_1_1_solvers.html", null ],
    [ "ptof::model_advection_diffusion_2d::Solvers", "d0/d22/structptof_1_1model__advection__diffusion__2d_1_1_solvers.html", null ],
    [ "geometry::Sphere< Position_t >", "d5/da0/structgeometry_1_1_sphere.html", null ],
    [ "ptof::State1D< Info_t, Time_t, Mass_t, Tag_t >", "d9/daf/structptof_1_1_state1_d.html", null ],
    [ "ptof::State1D_Periodic< Info_t, Time_t, Mass_t, Tag_t >", "d0/d12/structptof_1_1_state1_d___periodic.html", null ],
    [ "ptof::State2D< Info_t, Time_t, Mass_t, Tag_t >", "d1/d58/structptof_1_1_state2_d.html", null ],
    [ "ptof::State2D_Periodic< Info_t, Time_t, Mass_t, Tag_t >", "d0/d68/structptof_1_1_state2_d___periodic.html", null ],
    [ "ptof::State3D< Info_t, Time_t, Mass_t, Tag_t >", "df/de9/structptof_1_1_state3_d.html", null ],
    [ "ptof::State3D_Periodic< Info_t, Time_t, Mass_t, Tag_t >", "da/d6a/structptof_1_1_state3_d___periodic.html", null ],
    [ "ctrw::State_Periodic< Position_t, Periodicity_t, Mass_t, Time_t, Tag_t >", "d3/da4/structctrw_1_1_state___periodic.html", null ],
    [ "ctrw::State_position< Position_t, Time_t, Tag_t >", "d9/d28/structctrw_1_1_state__position.html", null ],
    [ "State_Position", "df/d93/struct_state___position.html", null ],
    [ "ctrw::State_Position_Mass< Position_t, Mass_t, Time_t, Tag_t >", "de/d11/structctrw_1_1_state___position___mass.html", null ],
    [ "ctrw::State_PTRW_Position< Position_t >", "df/ddd/structctrw_1_1_state___p_t_r_w___position.html", null ],
    [ "ctrw::State_RunTumble< Orientation_t, Tag_t >", "d0/d9a/structctrw_1_1_state___run_tumble.html", null ],
    [ "ctrw::State_RunTumble_PTRW< Orientation_t, Tag_t, Position_t >", "d3/d83/structctrw_1_1_state___run_tumble___p_t_r_w.html", null ],
    [ "ctrw::State_Velocity< Position_t, Velocity_t, Time_t, Tag_t >", "db/dc9/structctrw_1_1_state___velocity.html", null ],
    [ "ctrw::State_Velocity_Mass< Position_t, Velocity_t, Mass_t, Time_t, Tag_t >", "dd/d81/structctrw_1_1_state___velocity___mass.html", null ],
    [ "ptof::Steppers_Advection_Euler_Diffusion_Euler", "d3/d75/structptof_1_1_steppers___advection___euler___diffusion___euler.html", null ],
    [ "ptof::Steppers_Advection_RK4_Diffusion_Euler", "d7/dce/structptof_1_1_steppers___advection___r_k4___diffusion___euler.html", null ],
    [ "useful::Store< Object_Type, Return_Type >", "d3/d06/structuseful_1_1_store.html", null ],
    [ "ptof::Store_Absorbed", "d6/dee/structptof_1_1_store___absorbed.html", null ],
    [ "ptof::Store_Absorbed_Reinjections", "de/dbb/structptof_1_1_store___absorbed___reinjections.html", null ],
    [ "ptof::Store_Info_Contact", "d0/d38/structptof_1_1_store___info___contact.html", null ],
    [ "ptof::Store_Nothing", "de/df6/structptof_1_1_store___nothing.html", null ],
    [ "ptof::Store_Type", "d9/dcd/structptof_1_1_store___type.html", null ],
    [ "useful::StoreConst< Object_Type, Return_Type >", "db/d1e/structuseful_1_1_store_const.html", null ],
    [ "ptof::SurfaceReaction_AFluidPlusASolidtoASolid", "d4/d30/classptof_1_1_surface_reaction___a_fluid_plus_a_solidto_a_solid.html", null ],
    [ "ptof::SurfaceReaction_DoNothing", "df/d31/classptof_1_1_surface_reaction___do_nothing.html", null ],
    [ "geometry::SymmetryPlanes_Bcc", "da/dce/structgeometry_1_1_symmetry_planes___bcc.html", null ],
    [ "geometry::SymmetryPlanes_Sc", "d4/da0/structgeometry_1_1_symmetry_planes___sc.html", null ],
    [ "ctrw::CTRW< State_t >::Tag", "d8/dbf/structctrw_1_1_c_t_r_w_1_1_tag.html", null ],
    [ "ctrw::CTRW_Parallel< State_t >::Tag", "d9/da3/structctrw_1_1_c_t_r_w___parallel_1_1_tag.html", null ],
    [ "ctrw::TimeGenerator_Dist< Dist, RNG >", "dd/d51/classctrw_1_1_time_generator___dist.html", null ],
    [ "ctrw::TimeGenerator_Step< val_type >", "d1/d01/classctrw_1_1_time_generator___step.html", null ],
    [ "ctrw::TimeGenerator_Step< double >", "d1/d01/classctrw_1_1_time_generator___step.html", null ],
    [ "TimeStepAdaptor_CellSize", "d9/da7/class_time_step_adaptor___cell_size.html", null ],
    [ "ptof::TimeStepAdaptor_CellSize_SurfaceReaction< Geometry, VelocityField, SurfaceReaction, TransportParameters, ReactionParameters, SolverParameters, check_if_outside, warn_if_outside >", "d0/d9a/classptof_1_1_time_step_adaptor___cell_size___surface_reaction.html", null ],
    [ "Transition_Time_Position", "d8/dc1/class_transition___time___position.html", null ],
    [ "ctrw::Transitions_AdaptiveTimeStep_Time_Position< TimeStepAdaptor, TimeGenerator, JumpGenerator, Boundary >", "db/dad/classctrw_1_1_transitions___adaptive_time_step___time___position.html", null ],
    [ "ctrw::Transitions_CTRW_Transport_Reaction< Transitions_Transport, Reaction >", "db/dbd/classctrw_1_1_transitions___c_t_r_w___transport___reaction.html", null ],
    [ "ctrw::Transitions_Position< JumpGenerator, Boundary >", "d7/d1d/classctrw_1_1_transitions___position.html", null ],
    [ "ctrw::Transitions_Position_VelocityStep< JumpGenerator, VelocityField, Boundary >", "de/de9/classctrw_1_1_transitions___position___velocity_step.html", null ],
    [ "Transitions_Positions", "d5/da5/class_transitions___positions.html", null ],
    [ "ctrw::Transitions_PTRW_Diffusion_1d< Boundary, RNG >", "d8/da3/classctrw_1_1_transitions___p_t_r_w___diffusion__1d.html", null ],
    [ "ctrw::Transitions_PTRW_FlowField_Diff< FlowField, Boundary, RNG >", "d0/df3/classctrw_1_1_transitions___p_t_r_w___flow_field___diff.html", null ],
    [ "ctrw::Transitions_PTRW_Transport_Reaction< Transitions_Transport, Reaction >", "dc/db1/classctrw_1_1_transitions___p_t_r_w___transport___reaction.html", null ],
    [ "ctrw::Transitions_Reaction_Position< TimeGenerator, JumpGenerator, Reaction >", "d8/d5f/classctrw_1_1_transitions___reaction___position.html", null ],
    [ "ctrw::Transitions_Reaction_Position_Conditional< TimeGenerator, JumpGenerator, Reaction >", "d5/dd3/classctrw_1_1_transitions___reaction___position___conditional.html", null ],
    [ "ctrw::Transitions_RunAndTumble< TimeGenerator_run, TimeGenerator_tumble, JumpGenerator, OrientationGenerator >", "d6/d56/classctrw_1_1_transitions___run_and_tumble.html", null ],
    [ "ctrw::Transitions_RunAndTumble_PTRW< Boundary, StateSwitcher, JumpGenerator, OrientationGenerator, OrientationGenerator_Wall >", "da/d89/classctrw_1_1_transitions___run_and_tumble___p_t_r_w.html", null ],
    [ "Transitions_RunTumble", "db/dbe/class_transitions___run_tumble.html", null ],
    [ "ctrw::Transitions_Time_Position< TimeGenerator, JumpGenerator, Boundary >", "d4/d94/classctrw_1_1_transitions___time___position.html", null ],
    [ "ctrw::Transitions_Velocity_Acceleration< Acceleration, Boundary >", "db/d5a/classctrw_1_1_transitions___velocity___acceleration.html", null ],
    [ "ptof::model_advection_2d::Transport", "db/dc2/structptof_1_1model__advection__2d_1_1_transport.html", null ],
    [ "ptof::model_advection_diffusion_2d::Transport", "da/d36/structptof_1_1model__advection__diffusion__2d_1_1_transport.html", null ],
    [ "ptof::model_bcc_cartesian_advection::Transport", "df/d88/structptof_1_1model__bcc__cartesian__advection_1_1_transport.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion::Transport", "d2/da7/structptof_1_1model__bcc__cartesian__advection__diffusion_1_1_transport.html", null ],
    [ "std::true_type", null, [
      [ "ptof::Has_periodicity< State, decltype((void) State::periodicity, 0)>", "de/ddc/structptof_1_1_has__periodicity_3_01_state_00_01decltype_07_07void_08_01_state_1_1periodicity_00_010_08_4.html", null ],
      [ "useful::can_call_abs< std::void_t< decltype(std::abs(std::declval< Args >()...))>, Args... >", "dd/d7a/structuseful_1_1can__call__abs_3_01std_1_1void__t_3_01decltype_07std_1_1abs_07std_1_1declval_3_09601e9b67dd27b3a4cf3f7c54a97df9b.html", null ],
      [ "useful::can_call_sqrt< std::void_t< decltype(std::sqrt(std::declval< Args >()...))>, Args... >", "d7/d36/structuseful_1_1can__call__sqrt_3_01std_1_1void__t_3_01decltype_07std_1_1sqrt_07std_1_1declval_3f39161ab8e763816eedc8e73fc5ae026.html", null ],
      [ "useful::details::has_method< Z, types< Ts... >, void_t< Z< Ts... > > >", "d5/d8a/structuseful_1_1details_1_1has__method_3_01_z_00_01types_3_01_ts_8_8_8_01_4_00_01void__t_3_01_z_3_01_ts_8_8_8_01_4_01_4_01_4.html", null ]
    ] ],
    [ "useful::has_value_type< T >::Two", "dd/d71/structuseful_1_1has__value__type_1_1_two.html", null ],
    [ "useful::types<... >", "dc/d50/structuseful_1_1types.html", null ],
    [ "ptof::VectorField_LinearInterpolation_OF< Field, Locator, check_if_outside, warn_if_outside, Uninterpolated >", "d8/d71/classptof_1_1_vector_field___linear_interpolation___o_f.html", null ],
    [ "ctrw::VelocityFromGenerator< JumpGenerator >", "d6/d82/structctrw_1_1_velocity_from_generator.html", null ],
    [ "useful::voider<... >", "d2/dac/structuseful_1_1voider.html", null ]
];