var hierarchy =
[
    [ "ptof::Boundary_Cases< Locator, Store_Info, Boundary_Periodic, Boundary_Custom, SurfaceReaction >", "d4/d49/classptof_1_1_boundary___cases.html", null ],
    [ "geom::Boundary_DoNothing", "d2/df1/classgeom_1_1_boundary___do_nothing.html", null ],
    [ "ptof::Boundary_DoNothing", "d6/d3e/structptof_1_1_boundary___do_nothing.html", null ],
    [ "geom::Boundary_Open_RadialReflecting_3d< dd_open >", "df/db5/classgeom_1_1_boundary___open___radial_reflecting__3d.html", null ],
    [ "geom::Boundary_Periodic", "d8/d1f/classgeom_1_1_boundary___periodic.html", null ],
    [ "geom::Boundary_Periodic_1d", "df/df5/classgeom_1_1_boundary___periodic__1d.html", null ],
    [ "geom::Boundary_Periodic_Dim< dd >", "d4/d66/classgeom_1_1_boundary___periodic___dim.html", null ],
    [ "ptof::Boundary_Periodic_OF< Boundary, Locator >", "df/d60/structptof_1_1_boundary___periodic___o_f.html", null ],
    [ "geom::Boundary_Periodic_SymmetryPlanes< SymmetryPlanes >", "d9/d18/classgeom_1_1_boundary___periodic___symmetry_planes.html", null ],
    [ "geom::Boundary_Periodic_SymmetryPlanes_WithOutsideInfo< SymmetryPlanes >", "d7/d1b/classgeom_1_1_boundary___periodic___symmetry_planes___with_outside_info.html", null ],
    [ "geom::Boundary_Periodic_WithOutsideInfo", "d8/d11/classgeom_1_1_boundary___periodic___with_outside_info.html", null ],
    [ "geom::Boundary_RadialReflecting_2d", "de/dd9/classgeom_1_1_boundary___radial_reflecting__2d.html", null ],
    [ "geom::Boundary_Reflecting", "db/dcb/classgeom_1_1_boundary___reflecting.html", null ],
    [ "geom::Boundary_Reflecting_1d", "d6/d53/classgeom_1_1_boundary___reflecting__1d.html", null ],
    [ "geom::Boundary_Reflecting_Dim< dd >", "de/dc7/classgeom_1_1_boundary___reflecting___dim.html", null ],
    [ "ptof::Boundary_Reinject< InitialCondition >", "d4/d7b/structptof_1_1_boundary___reinject.html", null ],
    [ "ptof::BoundaryCondition", "d2/d5e/structptof_1_1_boundary_condition.html", null ],
    [ "ptof::BulkReaction_DoNothing", "dd/d75/classptof_1_1_bulk_reaction___do_nothing.html", null ],
    [ "Check", "de/df2/class_check.html", null ],
    [ "Check", "d2/df7/struct_check_options_1_1_check.html", null ],
    [ "ptof::CheckOptions::Check", "d3/d51/structptof_1_1_check_options_1_1_check.html", null ],
    [ "ptof::CheckOptions", "d3/d06/structptof_1_1_check_options.html", null ],
    [ "useful::Creator< T >", "d5/d03/structuseful_1_1_creator.html", null ],
    [ "ptof::Criterion< Subject >", "d9/d13/structptof_1_1_criterion.html", [
      [ "ptof::Criterion_all_absorbed< Subject >", "da/d25/structptof_1_1_criterion__all__absorbed.html", null ],
      [ "ptof::Criterion_fraction_not_absorbed< Subject >", "d7/db0/structptof_1_1_criterion__fraction__not__absorbed.html", null ],
      [ "ptof::Criterion_mass_above< Subject >", "d0/d36/structptof_1_1_criterion__mass__above.html", null ],
      [ "ptof::Criterion_mass_below< Subject >", "da/df1/structptof_1_1_criterion__mass__below.html", null ],
      [ "ptof::Criterion_one_absorbed< Subject >", "dc/df3/structptof_1_1_criterion__one__absorbed.html", null ],
      [ "ptof::Criterion_time< Subject >", "da/d6e/structptof_1_1_criterion__time.html", null ]
    ] ],
    [ "ctrw::CTRW< State_t >", "d2/dd2/classctrw_1_1_c_t_r_w.html", null ],
    [ "ctrw::CTRW_Parallel< State_t >", "d7/dfc/classctrw_1_1_c_t_r_w___parallel.html", null ],
    [ "ptof::Directories", "df/d68/structptof_1_1_directories.html", null ],
    [ "ptof::DirectoriesOF", "d1/d82/structptof_1_1_directories_o_f.html", null ],
    [ "useful::DoFalse", "d0/d9c/structuseful_1_1_do_false.html", null ],
    [ "geom::Domain< Shape >", "d6/d91/structgeom_1_1_domain.html", null ],
    [ "useful::DoNothing", "db/d72/structuseful_1_1_do_nothing.html", null ],
    [ "useful::DoTrue", "df/df3/structuseful_1_1_do_true.html", null ],
    [ "ptof::Dynamics", "d9/d9c/structptof_1_1_dynamics.html", null ],
    [ "useful::Empty", "da/d86/structuseful_1_1_empty.html", null ],
    [ "ptof::EndCriterion", "dd/d0d/structptof_1_1_end_criterion.html", null ],
    [ "std::false_type", null, [
      [ "meta::can_call_abs< typename, Args >", "d8/d2a/structmeta_1_1can__call__abs.html", null ],
      [ "meta::can_call_sqrt< typename, Args >", "da/dd4/structmeta_1_1can__call__sqrt.html", null ],
      [ "meta::has_member_impl< Z, types, typename >", "db/d1b/structmeta_1_1has__member__impl.html", null ]
    ] ],
    [ "useful::Forward< Object_Type >", "df/d34/structuseful_1_1_forward.html", null ],
    [ "useful::Forward< double >", "df/d34/structuseful_1_1_forward.html", null ],
    [ "useful::Forward_ref< Object_Type >", "d6/d37/structuseful_1_1_forward__ref.html", null ],
    [ "ptof::Geometry< dim_val, dynamics, SearchOption >", "dc/d30/structptof_1_1_geometry.html", null ],
    [ "ptof::Geometry_Bcc< periodicity, dynamics, SearchOption >", "da/d9d/structptof_1_1_geometry___bcc.html", null ],
    [ "ptof::Geometry_Bcc_Parallel< periodicity, dynamics, SearchOption >", "d1/d3e/structptof_1_1_geometry___bcc___parallel.html", null ],
    [ "ptof::Geometry_Parallel< dim_val, dynamics, SearchOption >", "df/dfc/structptof_1_1_geometry___parallel.html", null ],
    [ "ptof::Geometry_Periodic_Cartesian< dim_val, dynamics, SearchOption >", "d2/d99/structptof_1_1_geometry___periodic___cartesian.html", null ],
    [ "ptof::Geometry_Periodic_Cartesian_Parallel< dim_val, dynamics, SearchOption >", "df/dae/structptof_1_1_geometry___periodic___cartesian___parallel.html", null ],
    [ "ctrw::Get_dist_sq", "d2/d87/structctrw_1_1_get__dist__sq.html", null ],
    [ "ctrw::Get_from_particle< Getter >", "dd/db1/structctrw_1_1_get__from__particle.html", null ],
    [ "ctrw::Get_mass", "de/d1b/structctrw_1_1_get__mass.html", null ],
    [ "ctrw::Get_new< Getter >", "d0/dc3/structctrw_1_1_get__new.html", null ],
    [ "ctrw::Get_new_from_particle< Getter >", "dc/d51/structctrw_1_1_get__new__from__particle.html", null ],
    [ "ctrw::Get_old< Getter >", "dd/d08/structctrw_1_1_get__old.html", null ],
    [ "ctrw::Get_old_from_particle< Getter >", "db/df8/structctrw_1_1_get__old__from__particle.html", null ],
    [ "ctrw::Get_position", "d9/dca/structctrw_1_1_get__position.html", null ],
    [ "ctrw::Get_position_component< dd >", "d0/d8e/structctrw_1_1_get__position__component.html", null ],
    [ "ctrw::Get_position_component_arg", "de/d54/structctrw_1_1_get__position__component__arg.html", null ],
    [ "ctrw::Get_position_component_sq< dd >", "df/d0b/structctrw_1_1_get__position__component__sq.html", null ],
    [ "ctrw::Get_position_interp_velocity< Getter, Getter_velocity >", "d7/d1a/structctrw_1_1_get__position__interp__velocity.html", null ],
    [ "ctrw::Get_position_periodic< Boundary >", "dd/dd1/structctrw_1_1_get__position__periodic.html", null ],
    [ "ctrw::Get_position_periodic< Boundary const & >", "dd/dd1/structctrw_1_1_get__position__periodic.html", null ],
    [ "ctrw::Get_position_periodic_cartesian", "d7/dda/structctrw_1_1_get__position__periodic__cartesian.html", null ],
    [ "ctrw::Get_position_periodic_cartesian_component< dd >", "d4/d43/structctrw_1_1_get__position__periodic__cartesian__component.html", null ],
    [ "ctrw::Get_position_periodic_cartesian_projection", "d9/d7f/structctrw_1_1_get__position__periodic__cartesian__projection.html", null ],
    [ "ctrw::Get_position_projection", "da/dd1/structctrw_1_1_get__position__projection.html", null ],
    [ "ctrw::Get_position_property< Property >", "d0/d9a/structctrw_1_1_get__position__property.html", null ],
    [ "ctrw::Get_projection< Getter >", "df/de2/structctrw_1_1_get__projection.html", null ],
    [ "ctrw::Get_tag", "d5/daf/structctrw_1_1_get__tag.html", null ],
    [ "ctrw::Get_time", "da/dad/structctrw_1_1_get__time.html", null ],
    [ "ctrw::Get_time_interp_velocity< Getter, VelocityMapper >", "d5/d10/structctrw_1_1_get__time__interp__velocity.html", null ],
    [ "ctrw::Get_velocity", "d1/d4e/structctrw_1_1_get__velocity.html", null ],
    [ "ctrw::Get_velocity_component< dd >", "de/d39/structctrw_1_1_get__velocity__component.html", null ],
    [ "ctrw::Get_velocity_property< Property >", "d9/d1a/structctrw_1_1_get__velocity__property.html", null ],
    [ "useful::hash_container< Container >", "d4/de0/structuseful_1_1hash__container.html", null ],
    [ "useful::hash_pair< S, T >", "dc/d50/structuseful_1_1hash__pair.html", null ],
    [ "meta::indices< Indices >", "d5/d37/structmeta_1_1indices.html", null ],
    [ "ptof::Info_Absorbed", "d6/df0/structptof_1_1_info___absorbed.html", null ],
    [ "ptof::Info_Absorbed_Reinjections", "dc/d06/structptof_1_1_info___absorbed___reinjections.html", null ],
    [ "Info_type", "d4/d6e/struct_info__type.html", null ],
    [ "ptof::Info_Type", "d8/d13/structptof_1_1_info___type.html", null ],
    [ "ptof::model_advection_diffusion_2d::InitialCondition", "df/d07/structptof_1_1model__advection__diffusion__2d_1_1_initial_condition.html", null ],
    [ "ptof::InitialCondition_Cases< Geometry, VelocityField, ParticleMaker, Mask >", "db/dfb/classptof_1_1_initial_condition___cases.html", null ],
    [ "ptof::InitialConditionParameters_Cases", "dd/d20/structptof_1_1_initial_condition_parameters___cases.html", null ],
    [ "ptof::InitialConditions", "d5/d77/structptof_1_1_initial_conditions.html", null ],
    [ "meta::is_arithmetic< X, Y >", "d1/d84/structmeta_1_1is__arithmetic.html", null ],
    [ "meta::is_constructible_from_size_impl< X >", "d0/d30/structmeta_1_1is__constructible__from__size__impl.html", null ],
    [ "meta::is_convertible_from_abs_impl< X, Y >", "df/d22/structmeta_1_1is__convertible__from__abs__impl.html", null ],
    [ "meta::is_convertible_from_divides_impl< X, Y, Z >", "d7/d2c/structmeta_1_1is__convertible__from__divides__impl.html", null ],
    [ "meta::is_convertible_from_minus_impl< X, Y, Z >", "d3/d29/structmeta_1_1is__convertible__from__minus__impl.html", null ],
    [ "meta::is_convertible_from_multiplies_impl< X, Y, Z >", "d3/dcc/structmeta_1_1is__convertible__from__multiplies__impl.html", null ],
    [ "meta::is_convertible_from_plus_impl< X, Y, Z >", "dd/d50/structmeta_1_1is__convertible__from__plus__impl.html", null ],
    [ "meta::is_convertible_from_sqrt_impl< X, Y >", "d2/dfd/structmeta_1_1is__convertible__from__sqrt__impl.html", null ],
    [ "is_convertible_from_times_impl", "d2/dfa/classis__convertible__from__times__impl.html", null ],
    [ "meta::is_same< X, Y, Z >", "dd/d94/structmeta_1_1is__same.html", null ],
    [ "ctrw::JumpGenerator_Add< JumpGenerator_1, JumpGenerator_2 >", "d8/dd5/classctrw_1_1_jump_generator___add.html", null ],
    [ "ctrw::JumpGenerator_Diffusion", "df/d00/classctrw_1_1_jump_generator___diffusion.html", null ],
    [ "ctrw::JumpGenerator_Diffusion_1d< RNG >", "d1/d8b/classctrw_1_1_jump_generator___diffusion__1d.html", null ],
    [ "ctrw::JumpGenerator_Diffusion_1d< std::mt19937 >", "d1/d8b/classctrw_1_1_jump_generator___diffusion__1d.html", null ],
    [ "ctrw::JumpGenerator_JumpAngle_2d", "d4/def/classctrw_1_1_jump_generator___jump_angle__2d.html", null ],
    [ "ctrw::JumpGenerator_RW_1d< Distance_type, RNG >", "dd/d88/classctrw_1_1_jump_generator___r_w__1d.html", null ],
    [ "ctrw::JumpGenerator_Step< Step >", "d3/da3/classctrw_1_1_jump_generator___step.html", null ],
    [ "ctrw::JumpGenerator_Uniform_1d< RNG >", "d1/d43/classctrw_1_1_jump_generator___uniform__1d.html", null ],
    [ "ctrw::JumpGenerator_Velocity< VelocityField >", "d3/d4c/classctrw_1_1_jump_generator___velocity.html", null ],
    [ "ctrw::JumpGenerator_Velocity_RK4< VelocityField, Boundary >", "df/dcd/classctrw_1_1_jump_generator___velocity___r_k4.html", null ],
    [ "meta::notstd::left_shift", "d0/d34/structmeta_1_1notstd_1_1left__shift.html", null ],
    [ "ptof::Locator_Cell< SearchOption >", "d0/d4f/structptof_1_1_locator___cell.html", null ],
    [ "ptof::Locator_Cell< SearchOptions::SecondNeighborPrecheck >", "d0/d4f/structptof_1_1_locator___cell.html", null ],
    [ "ptof::Locator_Cell_Parallel< SearchOption >", "d5/db8/structptof_1_1_locator___cell___parallel.html", null ],
    [ "ptof::Locator_Cell_Parallel< SearchOptions::SecondNeighborPrecheck >", "d5/db8/structptof_1_1_locator___cell___parallel.html", null ],
    [ "useful::Maker< Object >", "dc/d8a/structuseful_1_1_maker.html", null ],
    [ "ptof::Measure", "dd/ddd/structptof_1_1_measure.html", null ],
    [ "ptof::OutputParameters_Cases::Measurement", "df/d93/structptof_1_1_output_parameters___cases_1_1_measurement.html", null ],
    [ "ptof::MeasureSpacing", "d4/dd7/structptof_1_1_measure_spacing.html", null ],
    [ "ptof::MeasureSpacingUnits", "d2/d80/structptof_1_1_measure_spacing_units.html", null ],
    [ "ptof::model_advection_2d::Model", "d3/df2/structptof_1_1model__advection__2d_1_1_model.html", null ],
    [ "ptof::model_advection_2d_parallel::Model", "d0/d0f/structptof_1_1model__advection__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_3d::Model", "dc/d30/structptof_1_1model__advection__3d_1_1_model.html", null ],
    [ "ptof::model_advection_3d_parallel::Model", "d6/d50/structptof_1_1model__advection__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_2d::Model", "d8/d28/structptof_1_1model__advection__diffusion__2d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_2d_parallel::Model", "d2/d0a/structptof_1_1model__advection__diffusion__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_3d::Model", "d3/df7/structptof_1_1model__advection__diffusion__3d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_3d_parallel::Model", "d3/df6/structptof_1_1model__advection__diffusion__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_fpt_2d::Model", "db/d89/structptof_1_1model__advection__diffusion__fpt__2d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_fpt_2d_parallel::Model", "d7/db8/structptof_1_1model__advection__diffusion__fpt__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_fpt_3d::Model", "d8/d2a/structptof_1_1model__advection__diffusion__fpt__3d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_fpt_3d_parallel::Model", "dc/d6c/structptof_1_1model__advection__diffusion__fpt__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_2d::Model", "d0/da7/structptof_1_1model__advection__diffusion__surface__decay__2d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_2d_parallel::Model", "db/da2/structptof_1_1model__advection__diffusion__surface__decay__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_3d::Model", "d6/d5a/structptof_1_1model__advection__diffusion__surface__decay__3d_1_1_model.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_3d_parallel::Model", "d0/da6/structptof_1_1model__advection__diffusion__surface__decay__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection::Model", "dd/d1b/structptof_1_1model__bcc__cartesian__advection_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion::Model", "d2/da9/structptof_1_1model__bcc__cartesian__advection__diffusion_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_fpt::Model", "db/d65/structptof_1_1model__bcc__cartesian__advection__diffusion__fpt_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_fpt_parallel::Model", "d6/d55/structptof_1_1model__bcc__cartesian__advection__diffusion__fpt__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_parallel::Model", "df/d52/structptof_1_1model__bcc__cartesian__advection__diffusion__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_surface_decay::Model", "d5/d44/structptof_1_1model__bcc__cartesian__advection__diffusion__surface__decay_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion_surface_decay_parallel::Model", "d6/dfa/structptof_1_1model__bcc__cartesian__advection__diffusion__surface__decay__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_cartesian_advection_parallel::Model", "dc/d22/structptof_1_1model__bcc__cartesian__advection__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection::Model", "dd/d30/structptof_1_1model__bcc__symmetryplanes__advection_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion::Model", "db/d17/structptof_1_1model__bcc__symmetryplanes__advection__diffusion_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_fpt::Model", "d8/d11/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__fpt_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_fpt_parallel::Model", "d8/d8d/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__fpt__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_parallel::Model", "d8/d58/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_surface_decay::Model", "d1/dd3/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__surface__decay_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_diffusion_surface_decay_parallel::Model", "da/d03/structptof_1_1model__bcc__symmetryplanes__advection__diffusion__surface__decay__parallel_1_1_model.html", null ],
    [ "ptof::model_bcc_symmetryplanes_advection_parallel::Model", "d6/d83/structptof_1_1model__bcc__symmetryplanes__advection__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_2d::Model", "de/dd4/structptof_1_1model__periodic__cartesian__advection__2d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_2d_parallel::Model", "d3/dd9/structptof_1_1model__periodic__cartesian__advection__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_3d::Model", "d5/d4f/structptof_1_1model__periodic__cartesian__advection__3d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_3d_parallel::Model", "d5/db1/structptof_1_1model__periodic__cartesian__advection__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_2d::Model", "d3/da7/structptof_1_1model__periodic__cartesian__advection__diffusion__2d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_2d_parallel::Model", "da/d86/structptof_1_1model__periodic__cartesian__advection__diffusion__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_3d::Model", "d5/d26/structptof_1_1model__periodic__cartesian__advection__diffusion__3d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_3d_parallel::Model", "d7/d62/structptof_1_1model__periodic__cartesian__advection__diffusion__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_fpt_2d::Model", "dc/d39/structptof_1_1model__periodic__cartesian__advection__diffusion__fpt__2d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_fpt_2d_parallel::Model", "d2/dcd/structptof_1_1model__periodic__cartesian__advection__diffusion__fpt__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_fpt_3d::Model", "dc/d32/structptof_1_1model__periodic__cartesian__advection__diffusion__fpt__3d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_fpt_3d_parallel::Model", "d0/d77/structptof_1_1model__periodic__cartesian__advection__diffusion__fpt__3d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_surface_decay_2d::Model", "de/dd0/structptof_1_1model__periodic__cartesian__advection__diffusion__surface__decay__2d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_surface_decay_2d_parallel::Model", "df/d2e/structptof_1_1model__periodic__cartesian__advection__diffusion__surface__decay__2d__parallel_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_surface_decay_3d::Model", "d1/d0c/structptof_1_1model__periodic__cartesian__advection__diffusion__surface__decay__3d_1_1_model.html", null ],
    [ "ptof::model_periodic_cartesian_advection_diffusion_surface_decay_3d_parallel::Model", "d1/d26/structptof_1_1model__periodic__cartesian__advection__diffusion__surface__decay__3d__parallel_1_1_model.html", null ],
    [ "useful::MultiArray< value_t >", "dc/d1a/classuseful_1_1_multi_array.html", null ],
    [ "ptof::SearchOptions::NeighborPrecheck< level >", "da/dd0/structptof_1_1_search_options_1_1_neighbor_precheck.html", null ],
    [ "NeighborPrecheck", "d1/df9/class_search_options_1_1_neighbor_precheck.html", null ],
    [ "NextMeasureTime", "de/da1/struct_output___cases_1_1_next_measure_time.html", null ],
    [ "ptof::Output_Cases< Subject, Geometry >::NextMeasureTime", "de/da7/structptof_1_1_output___cases_1_1_next_measure_time.html", [
      [ "ptof::Output_Cases< Subject, Geometry >::NextMeasureTime_linear", "dc/d4b/structptof_1_1_output___cases_1_1_next_measure_time__linear.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::NextMeasureTime_log", "d6/de0/structptof_1_1_output___cases_1_1_next_measure_time__log.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::NextMeasureTime_step", "db/de3/structptof_1_1_output___cases_1_1_next_measure_time__step.html", null ]
    ] ],
    [ "NextMeasureTime_log", "de/d81/struct_output___cases_1_1_next_measure_time__log.html", null ],
    [ "NextMeasureTime_step", "d6/d19/struct_output___cases_1_1_next_measure_time__step.html", null ],
    [ "ptof::CheckOptions::NoCheck", "de/de1/structptof_1_1_check_options_1_1_no_check.html", null ],
    [ "NoChecl", "d5/d05/struct_check_options_1_1_no_checl.html", null ],
    [ "meta::op_valid< X, Y, Op >", "dd/de4/structmeta_1_1op__valid.html", null ],
    [ "meta::notstd::operator_and", "dc/d4e/structmeta_1_1notstd_1_1operator__and.html", null ],
    [ "ctrw::OrientationGenerator_Flip", "d0/d3d/classctrw_1_1_orientation_generator___flip.html", null ],
    [ "ctrw::OrientationGenerator_Gradient_1d< Concentration, Gradient, RNG >", "d0/d34/classctrw_1_1_orientation_generator___gradient__1d.html", null ],
    [ "Output", "d3/dc7/struct_output___cases_1_1_output.html", null ],
    [ "ptof::model_advection_diffusion_2d::Output", "d0/d89/structptof_1_1model__advection__diffusion__2d_1_1_output.html", null ],
    [ "ptof::Output_Cases< Subject, Geometry >::Output", "d0/d91/structptof_1_1_output___cases_1_1_output.html", [
      [ "ptof::Output_Cases< Subject, Geometry >::Output_absorption_time", "d8/d3c/structptof_1_1_output___cases_1_1_output__absorption__time.html", null ]
    ] ],
    [ "Output_absorption_time", "d6/da2/struct_output___cases_1_1_output__absorption__time.html", null ],
    [ "ptof::Output_Cases< Subject, Geometry >", "d5/de8/classptof_1_1_output___cases.html", null ],
    [ "Output_mass", "de/d7f/struct_output___cases_1_1_output__mass.html", null ],
    [ "Output_mass_in_regions", "de/d9c/class_output___cases_1_1_output__mass__in__regions.html", null ],
    [ "Output_position", "df/d5e/struct_output___cases_1_1_output__position.html", null ],
    [ "Output_position_in_regions", "dc/dfc/class_output___cases_1_1_output__position__in__regions.html", null ],
    [ "Output_position_in_regions_periodic", "dc/d1f/class_output___cases_1_1_output__position__in__regions__periodic.html", null ],
    [ "Output_position_mean", "d6/d70/struct_output___cases_1_1_output__position__mean.html", null ],
    [ "Output_position_mean_periodic", "da/dbc/class_output___cases_1_1_output__position__mean__periodic.html", null ],
    [ "Output_position_periodic", "d8/d7a/class_output___cases_1_1_output__position__periodic.html", null ],
    [ "Output_position_second_moment", "db/d24/struct_output___cases_1_1_output__position__second__moment.html", null ],
    [ "Output_position_second_moment_periodic", "d5/d3a/class_output___cases_1_1_output__position__second__moment__periodic.html", null ],
    [ "Output_position_variance", "dd/d84/struct_output___cases_1_1_output__position__variance.html", null ],
    [ "Output_position_variance_periodic", "d7/d3d/class_output___cases_1_1_output__position__variance__periodic.html", null ],
    [ "Output_scalar_field", "d5/d99/class_output___cases_1_1_output__scalar__field.html", null ],
    [ "Output_tensor_field", "dd/ddc/class_output___cases_1_1_output__tensor__field.html", null ],
    [ "Output_vector_field", "de/db0/class_output___cases_1_1_output__vector__field.html", null ],
    [ "ptof::OutputParameters_Cases", "d8/d12/structptof_1_1_output_parameters___cases.html", null ],
    [ "OutputTime", "da/d2f/struct_output___cases_1_1_output_time.html", null ],
    [ "ptof::Output_Cases< Subject, Geometry >::OutputTime", "d2/d71/structptof_1_1_output___cases_1_1_output_time.html", [
      [ "ptof::Output_Cases< Subject, Geometry >::Output_mass", "d3/da0/structptof_1_1_output___cases_1_1_output__mass.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_mass_in_regions< Mask >", "dd/d8c/structptof_1_1_output___cases_1_1_output__mass__in__regions.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position", "d3/ded/structptof_1_1_output___cases_1_1_output__position.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_in_regions< Mask >", "dd/dd4/structptof_1_1_output___cases_1_1_output__position__in__regions.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_in_regions_periodic< Mask >", "d5/d8c/structptof_1_1_output___cases_1_1_output__position__in__regions__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_mean", "d1/d2d/structptof_1_1_output___cases_1_1_output__position__mean.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_mean_periodic", "d3/d02/structptof_1_1_output___cases_1_1_output__position__mean__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_periodic", "d3/d84/structptof_1_1_output___cases_1_1_output__position__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_second_moment", "dc/dc1/structptof_1_1_output___cases_1_1_output__position__second__moment.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_second_moment_periodic", "da/d6d/structptof_1_1_output___cases_1_1_output__position__second__moment__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_variance", "d5/d2b/structptof_1_1_output___cases_1_1_output__position__variance.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_position_variance_periodic", "d7/dc2/structptof_1_1_output___cases_1_1_output__position__variance__periodic.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_scalar_field< Field >", "d8/d38/structptof_1_1_output___cases_1_1_output__scalar__field.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_tensor_field< Field >", "d0/da0/structptof_1_1_output___cases_1_1_output__tensor__field.html", null ],
      [ "ptof::Output_Cases< Subject, Geometry >::Output_vector_field< Field >", "d3/dbb/structptof_1_1_output___cases_1_1_output__vector__field.html", null ]
    ] ],
    [ "Parallel", "d3/d1f/struct_parallel_options_1_1_parallel.html", null ],
    [ "ptof::ParallelOptions::Parallel", "dc/da6/structptof_1_1_parallel_options_1_1_parallel.html", null ],
    [ "geom::Parallelepiped< Position_t >", "dd/df2/structgeom_1_1_parallelepiped.html", null ],
    [ "ptof::ParallelOptions", "d9/dbc/structptof_1_1_parallel_options.html", null ],
    [ "Parameters", "d4/d48/struct_phase_1_1_parameters.html", null ],
    [ "ptof::model_advection_2d::Solvers::Parameters", "d6/d3d/structptof_1_1model__advection__2d_1_1_solvers_1_1_parameters.html", null ],
    [ "ptof::model_advection_2d::Transport::Parameters", "d8/d0b/structptof_1_1model__advection__2d_1_1_transport_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_2d::Reaction::Parameters", "de/d70/structptof_1_1model__advection__diffusion__2d_1_1_reaction_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_2d::Solvers::Parameters", "dc/d05/structptof_1_1model__advection__diffusion__2d_1_1_solvers_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_2d::Transport::Parameters", "dc/d6a/structptof_1_1model__advection__diffusion__2d_1_1_transport_1_1_parameters.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_2d::Reaction::Parameters", "d2/d04/structptof_1_1model__advection__diffusion__surface__decay__2d_1_1_reaction_1_1_parameters.html", null ],
    [ "ptof::model_bcc_cartesian_advection::Transport::Parameters", "db/d87/structptof_1_1model__bcc__cartesian__advection_1_1_transport_1_1_parameters.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion::Transport::Parameters", "d4/d16/structptof_1_1model__bcc__cartesian__advection__diffusion_1_1_transport_1_1_parameters.html", null ],
    [ "ptof::Phase::Parameters", "de/d93/structptof_1_1_phase_1_1_parameters.html", null ],
    [ "meta::Parameters_or_empty< bool, typename >", "de/d1d/structmeta_1_1_parameters__or__empty.html", null ],
    [ "meta::Parameters_or_empty< true, T >", "d3/d54/structmeta_1_1_parameters__or__empty_3_01true_00_01_t_01_4.html", null ],
    [ "ctrw::Particle< State_t >", "d5/d4b/classctrw_1_1_particle.html", null ],
    [ "ptof::ParticleMaker< Particle, Locator >", "da/dae/structptof_1_1_particle_maker.html", null ],
    [ "ptof::ParticleMaker_Periodic< Particle, Locator, Boundary >", "d5/d84/structptof_1_1_particle_maker___periodic.html", null ],
    [ "ptof::Periodicity", "d3/dc2/structptof_1_1_periodicity.html", null ],
    [ "ptof::Phase", "d0/d06/structptof_1_1_phase.html", null ],
    [ "ptof::InitialCondition_Cases< Geometry, VelocityField, ParticleMaker, Mask >::PositionMaker", "dc/dab/structptof_1_1_initial_condition___cases_1_1_position_maker.html", null ],
    [ "ptof::model_advection_diffusion_2d::Reaction", "d4/d50/structptof_1_1model__advection__diffusion__2d_1_1_reaction.html", null ],
    [ "ptof::model_advection_diffusion_surface_decay_2d::Reaction", "d2/dcb/structptof_1_1model__advection__diffusion__surface__decay__2d_1_1_reaction.html", null ],
    [ "meta::notstd::right_shift", "d5/d72/structmeta_1_1notstd_1_1right__shift.html", null ],
    [ "ptof::ScalarField_LinearInterpolation_OF< Field, Locator, CheckOption, Uninterpolated >", "d6/d57/classptof_1_1_scalar_field___linear_interpolation___o_f.html", null ],
    [ "ptof::SearchOptions", "d7/d21/structptof_1_1_search_options.html", null ],
    [ "useful::Selector< TT, val >", "d7/dd2/structuseful_1_1_selector.html", null ],
    [ "useful::Selector_t< TT >", "d3/d42/structuseful_1_1_selector__t.html", null ],
    [ "Serial", "da/da3/struct_parallel_options_1_1_serial.html", null ],
    [ "ptof::ParallelOptions::Serial", "d3/d09/structptof_1_1_parallel_options_1_1_serial.html", null ],
    [ "ptof::model_advection_2d::Solvers", "df/d8b/structptof_1_1model__advection__2d_1_1_solvers.html", null ],
    [ "ptof::model_advection_diffusion_2d::Solvers", "d0/d22/structptof_1_1model__advection__diffusion__2d_1_1_solvers.html", null ],
    [ "geom::Sphere< Position_t >", "d0/da4/structgeom_1_1_sphere.html", null ],
    [ "ptof::State1D< Info_t, Time_t, Mass_t, Tag_t >", "d9/daf/structptof_1_1_state1_d.html", null ],
    [ "ptof::State1D_Periodic< Info_t, Time_t, Mass_t, Tag_t >", "d0/d12/structptof_1_1_state1_d___periodic.html", null ],
    [ "ptof::State2D< Info_t, Time_t, Mass_t, Tag_t >", "d1/d58/structptof_1_1_state2_d.html", null ],
    [ "ptof::State2D_Periodic< Info_t, Time_t, Mass_t, Tag_t >", "d0/d68/structptof_1_1_state2_d___periodic.html", null ],
    [ "ptof::State3D< Info_t, Time_t, Mass_t, Tag_t >", "df/de9/structptof_1_1_state3_d.html", null ],
    [ "ptof::State3D_Periodic< Info_t, Time_t, Mass_t, Tag_t >", "da/d6a/structptof_1_1_state3_d___periodic.html", null ],
    [ "ctrw::State_Periodic< Position_t, Periodicity_t, Mass_t, Time_t, Tag_t >", "d3/da4/structctrw_1_1_state___periodic.html", null ],
    [ "ctrw::State_position< Position_t, Time_t, Tag_t >", "d9/d28/structctrw_1_1_state__position.html", null ],
    [ "State_Position", "df/d93/struct_state___position.html", null ],
    [ "ctrw::State_Position_Mass< Position_t, Mass_t, Time_t, Tag_t >", "de/d11/structctrw_1_1_state___position___mass.html", null ],
    [ "ctrw::State_PTRW_Position< Position_t >", "df/ddd/structctrw_1_1_state___p_t_r_w___position.html", null ],
    [ "ctrw::State_RunTumble< Orientation_t, Tag_t >", "d0/d9a/structctrw_1_1_state___run_tumble.html", null ],
    [ "ctrw::State_RunTumble_PTRW< Orientation_t, Tag_t, Position_t >", "d3/d83/structctrw_1_1_state___run_tumble___p_t_r_w.html", null ],
    [ "ctrw::State_Velocity< Position_t, Velocity_t, Time_t, Tag_t >", "db/dc9/structctrw_1_1_state___velocity.html", null ],
    [ "ctrw::State_Velocity_Mass< Position_t, Velocity_t, Mass_t, Time_t, Tag_t >", "dd/d81/structctrw_1_1_state___velocity___mass.html", null ],
    [ "ptof::Steppers_Advection_Euler_Diffusion_Euler", "d3/d75/structptof_1_1_steppers___advection___euler___diffusion___euler.html", null ],
    [ "ptof::Steppers_Advection_RK4_Diffusion_Euler", "d7/dce/structptof_1_1_steppers___advection___r_k4___diffusion___euler.html", null ],
    [ "useful::Store< Object_Type, Return_Type >", "d3/d06/structuseful_1_1_store.html", null ],
    [ "ptof::Store_Absorbed", "d6/dee/structptof_1_1_store___absorbed.html", null ],
    [ "ptof::Store_Absorbed_Reinjections", "de/dbb/structptof_1_1_store___absorbed___reinjections.html", null ],
    [ "ptof::Store_Info_Contact", "d0/d38/structptof_1_1_store___info___contact.html", null ],
    [ "ptof::Store_Nothing", "de/df6/structptof_1_1_store___nothing.html", null ],
    [ "ptof::Store_Type", "d9/dcd/structptof_1_1_store___type.html", null ],
    [ "useful::StoreConst< Object_Type, Return_Type >", "db/d1e/structuseful_1_1_store_const.html", null ],
    [ "ptof::SurfaceReaction_AFluidPlusASolidtoASolid", "d4/d30/classptof_1_1_surface_reaction___a_fluid_plus_a_solidto_a_solid.html", null ],
    [ "ptof::SurfaceReaction_DoNothing", "df/d31/classptof_1_1_surface_reaction___do_nothing.html", null ],
    [ "geom::SymmetryPlanes_Bcc", "d3/dac/structgeom_1_1_symmetry_planes___bcc.html", null ],
    [ "geom::SymmetryPlanes_Sc", "dd/d48/structgeom_1_1_symmetry_planes___sc.html", null ],
    [ "ctrw::CTRW< State_t >::Tag", "d8/dbf/structctrw_1_1_c_t_r_w_1_1_tag.html", null ],
    [ "ctrw::CTRW_Parallel< State_t >::Tag", "d9/da3/structctrw_1_1_c_t_r_w___parallel_1_1_tag.html", null ],
    [ "ctrw::TimeGenerator_Dist< Dist, RNG >", "dd/d51/classctrw_1_1_time_generator___dist.html", null ],
    [ "ctrw::TimeGenerator_Step< val_type >", "d1/d01/classctrw_1_1_time_generator___step.html", null ],
    [ "ctrw::TimeGenerator_Step< double >", "d1/d01/classctrw_1_1_time_generator___step.html", null ],
    [ "TimeStepAdaptor_CellSize", "d9/da7/class_time_step_adaptor___cell_size.html", null ],
    [ "ptof::TimeStepAdaptor_CellSize_SurfaceReaction< Geometry, VelocityField, SurfaceReaction, TransportParameters, ReactionParameters, SolverParameters, CheckOption >", "d0/d9a/classptof_1_1_time_step_adaptor___cell_size___surface_reaction.html", null ],
    [ "Transition_Time_Position", "d8/dc1/class_transition___time___position.html", null ],
    [ "ctrw::Transitions_AdaptiveTimeStep_Time_Position< TimeStepAdaptor, TimeGenerator, JumpGenerator, Boundary >", "db/dad/classctrw_1_1_transitions___adaptive_time_step___time___position.html", null ],
    [ "ctrw::Transitions_CTRW_Transport_Reaction< Transitions_Transport, Reaction >", "db/dbd/classctrw_1_1_transitions___c_t_r_w___transport___reaction.html", null ],
    [ "ctrw::Transitions_Position< JumpGenerator, Boundary >", "d7/d1d/classctrw_1_1_transitions___position.html", null ],
    [ "ctrw::Transitions_Position_VelocityStep< JumpGenerator, VelocityField, Boundary >", "de/de9/classctrw_1_1_transitions___position___velocity_step.html", null ],
    [ "Transitions_Positions", "d5/da5/class_transitions___positions.html", null ],
    [ "ctrw::Transitions_PTRW_Diffusion_1d< Boundary, RNG >", "d8/da3/classctrw_1_1_transitions___p_t_r_w___diffusion__1d.html", null ],
    [ "ctrw::Transitions_PTRW_FlowField_Diff< FlowField, Boundary, RNG >", "d0/df3/classctrw_1_1_transitions___p_t_r_w___flow_field___diff.html", null ],
    [ "ctrw::Transitions_PTRW_Transport_Reaction< Transitions_Transport, Reaction >", "dc/db1/classctrw_1_1_transitions___p_t_r_w___transport___reaction.html", null ],
    [ "ctrw::Transitions_Reaction_Position< TimeGenerator, JumpGenerator, Reaction >", "d8/d5f/classctrw_1_1_transitions___reaction___position.html", null ],
    [ "ctrw::Transitions_Reaction_Position_Conditional< TimeGenerator, JumpGenerator, Reaction >", "d5/dd3/classctrw_1_1_transitions___reaction___position___conditional.html", null ],
    [ "ctrw::Transitions_RunAndTumble< TimeGenerator_run, TimeGenerator_tumble, JumpGenerator, OrientationGenerator >", "d6/d56/classctrw_1_1_transitions___run_and_tumble.html", null ],
    [ "ctrw::Transitions_RunAndTumble_PTRW< Boundary, StateSwitcher, JumpGenerator, OrientationGenerator, OrientationGenerator_Wall >", "da/d89/classctrw_1_1_transitions___run_and_tumble___p_t_r_w.html", null ],
    [ "Transitions_RunTumble", "db/dbe/class_transitions___run_tumble.html", null ],
    [ "ctrw::Transitions_Time_Position< TimeGenerator, JumpGenerator, Boundary >", "d4/d94/classctrw_1_1_transitions___time___position.html", null ],
    [ "ctrw::Transitions_Velocity_Acceleration< Acceleration, Boundary >", "db/d5a/classctrw_1_1_transitions___velocity___acceleration.html", null ],
    [ "ptof::model_advection_2d::Transport", "db/dc2/structptof_1_1model__advection__2d_1_1_transport.html", null ],
    [ "ptof::model_advection_diffusion_2d::Transport", "da/d36/structptof_1_1model__advection__diffusion__2d_1_1_transport.html", null ],
    [ "ptof::model_bcc_cartesian_advection::Transport", "df/d88/structptof_1_1model__bcc__cartesian__advection_1_1_transport.html", null ],
    [ "ptof::model_bcc_cartesian_advection_diffusion::Transport", "d2/da7/structptof_1_1model__bcc__cartesian__advection__diffusion_1_1_transport.html", null ],
    [ "std::true_type", null, [
      [ "meta::can_call_abs< std::void_t< decltype(std::abs(std::declval< Args >()...))>, Args... >", "d3/dbd/structmeta_1_1can__call__abs_3_01std_1_1void__t_3_01decltype_07std_1_1abs_07std_1_1declval_3_01_8378ae50039975643e5dcdd641310d1a.html", null ],
      [ "meta::can_call_sqrt< std::void_t< decltype(std::sqrt(std::declval< Args >()...))>, Args... >", "d0/d7d/structmeta_1_1can__call__sqrt_3_01std_1_1void__t_3_01decltype_07std_1_1sqrt_07std_1_1declval_3_08d5bfbec0d91a76f978aad0e97e9a8e3.html", null ],
      [ "meta::has_member_impl< Z, types< Ts... >, std::void_t< Z< Ts... > > >", "db/d68/structmeta_1_1has__member__impl_3_01_z_00_01types_3_01_ts_8_8_8_01_4_00_01std_1_1void__t_3_01_z_3_01_ts_8_8_8_01_4_01_4_01_4.html", null ]
    ] ],
    [ "meta::types<... >", "d7/dab/structmeta_1_1types.html", null ],
    [ "ptof::VectorField_LinearInterpolation_OF< Field, Locator, CheckOption, Uninterpolated >", "d8/d71/classptof_1_1_vector_field___linear_interpolation___o_f.html", null ],
    [ "ctrw::VelocityFromGenerator< JumpGenerator >", "d6/d82/structctrw_1_1_velocity_from_generator.html", null ],
    [ "Warn", "da/ded/struct_check_options_1_1_warn.html", null ],
    [ "ptof::CheckOptions::Warn", "d0/dd6/structptof_1_1_check_options_1_1_warn.html", null ]
];